### ISSUE TITLE
AttributeError: module 'asyncqlio.backends.mysql' has no attribute 'MysqlDialect'

### ISSUE THREAD

**Issue by dangerousfeng** [SunDwarf/asyncqlio#41]
`from asyncqlio import DatabaseInterface
import asyncio

async def hello():
    db = DatabaseInterface("mysql://root:123456@localhost:3306/user")
    await db.connect()
    async with db.get_transaction() as t:
        cur = await t.cursor("SELECT 1;")
        row = await cur.fetch_row()
        print(row)

if __name__=='__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(hello())`

**Comment by SunDwarf** [comment]
Fixed and a quick patch pushed to PyPI.
