### ISSUE TITLE
TIMESTAMP is not equal between PSQL and MySQL

### ISSUE THREAD

**Issue by marcoceppi** [SunDwarf/asyncqlio#43]
On PostgreSQL, TIMESTAMP is both a date and time record. In MySQL, TIMESTAMP is simply the time and not date. For equivalent/compatibility, MySQL driver should translate TIMESTAMP to DATETIME, or a DATETIME column type added.

**Comment by SunDwarf** [comment]
From the MySQL docs:

>  The TIMESTAMP data type is used for values that contain both date and time parts. TIMESTAMP has a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC. 

So this doesn't seem to be true?

**Comment by marcoceppi** [comment]
I have no idea how I missed that in the docs. Thank you!
