### ISSUE TITLE
Include decimal, double, numeric definitions

### ISSUE THREAD

**Issue by marcoceppi** [SunDwarf/asyncqlio#44]
Before opening a pull request I wanted to check on if this is something in the maintainers vision for the library. Today the only precision value type support by MySQL backend is `float` which maps to `orm.type.Real`. Our database contains quite a few columns that are `decimal(12,8)`. This size is outside what floats can normally sign - and given the choice between `double` and `decimal` we settled on the later.

I believe there is a case to be made for at a minimum mapping `decimal` and `double` in MySQL backend to `orm.type.Real`. However, given there is also a decimal type in PostgreSQL (`numeric`) which is slightly different than a `type.Real` I believe a `numeric` type might be worth inclusion with the following backend mappings:

| Backend  | Data Type | Library type | 
| ------------- | ------------- | ------------- |
| PostgreSQL  | decimal | numeric
| PostgreSQL  | numeric | numeric
| MySQL  | decimal | numeric
| MySQL  | double | numeric
| SQLite  | decimal | numeric
| SQLite  | numeric | numeric

Interested in opinions on the topic before I attempt any code updates.

**Comment by SunDwarf** [comment]
Sure, this works. The types in the library definitely aren't complete (just like the rest of it, really...) so I appreciate any attempt at filling them in. 

One thing is maybe the row type (`my_row.column`) should have an option for returning either a float or a `decimal.Decimal`, perhaps. SQLAlchemy (my gold standard of ORM design) allows for that, with an `asdecimal` param on it's Numeric constructor.
